version: '3' 
services:
  backend-ft:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend-ft
    restart: always
    ports:
      - 3000:3000
    env_file:
      - backend/.env
  frontend-ft:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend-ft
    restart: always
    depends_on:
      - backend-ft
    ports:
      - 80:80
    env_file:
      - frontend/.env